import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.special import binom


def fast_non_dominated_sort(population_coords):
    '''
    Accepts a list of coordinates of solutions in score space,
    for each solution instance:

    Returns its rank according to the sorting result.

    Returns list of fronts, each of which is a list of
    solutions. fronts[0] is the nondominated front.
    '''

    fronts = []
    fronts.append([])

    popsize = population_coords.shape[0]
    ranks = np.zeros((popsize,))
    domination_table = np.zeros((popsize, popsize), dtype='bool')
    dominated_cardinal = np.zeros((popsize,))

    '''
    For each solution, modify 'domination_table' where
    True at row i column j means that solution i dominates j.
    Assign a number of solutions that dominate solution i
    to 'dominated_cardinal[i]' field.
    '''
    for i, p in enumerate(population_coords):
        for j, q in enumerate(population_coords):
            domination = dominates(p,q)
            if domination == 1:
                domination_table[i, j] = True
            elif domination == -1:
                dominated_cardinal[i] += 1
        if dominated_cardinal[i] == 0:
            ranks[i] = 1
            fronts[0].append(i)

    '''
    Peel fronts one by one, from nondominated to
    the worst one.
    '''
    i = 0
    while len(fronts[i]) != 0:
        next_front = []
        for pi in fronts[i]:
            p = population_coords[pi]
            for qi in np.argwhere(domination_table[pi,:]==True).T[0]:
                q = population_coords[qi]
                dominated_cardinal[qi] -= 1
                if dominated_cardinal[qi] == 0:
                    ranks[qi] = i + 2
                    next_front.append(qi)
        i += 1
        fronts.append(next_front)

    return fronts, ranks


def dominates(p,q):
    '''
    Returns 1 if p dominates q, -1
    if q dominates p, 0 otherwise.
    '''
    if p[0] >= q[0] and p[1] >= q[1]:
        return 1
    elif p[0] <= q[0] and p[1] <= q[1]:
        return -1
    else:
        return 0


def get_reference_coords(div, dim):
    '''
    Generates a list of coordinates that divide each
    goal axis by specified number of divisions.
    '''

    start_vector = np.ones((div+1,))
    start_vector[:div] = np.arange(0,1,1/div)
    coords = np.array([(i,j) for i,j in zip(start_vector, reversed(start_vector))])

    for i in range(3,dim+1):
        coords_update = np.zeros((int(binom(i + div - 1, div)),i))
        reduction_vector = np.zeros((coords.shape[1],))
        reduction_vector[-1] = 1
        offset = 0
        for j in range(div + 1):
            reduced_coords = coords - reduction_vector * j * 1/div
            erase = np.argwhere(reduced_coords < -0.0000001)[:,0]
            reduced_coords = np.delete(reduced_coords, erase, axis=0)
            h, w = reduced_coords.shape
            coords_update[offset:offset+h,:i-1] = reduced_coords
            coords_update[offset:offset+h,i-1] = j*1/div
            offset += h
        coords = coords_update

    return coords


def normalize(candidate_scores, nondom_scores):
    '''
    Normalizes scores of candidate solutions according
    to NSGA-III specification.
    '''

    '''
    This fragment is almost entirely copied from
    official implementation by Deb and his students
    since the paper itself is not very clear on this calculation.

    It basically finds solutions that are closest to each axis
    among nondominated solutions. Resulting points are saved as
    'maximum' points.
    '''

    '''
    TODO: solve singular matrix
    '''

    ideal_point = np.min(candidate_scores, axis=0)
    weights = np.eye(candidate_scores.shape[1])
    weights[weights==0] = 1e6

    asf = np.max(nondom_scores * weights[:,None,:], axis=2)
    I = np.argmin(asf, axis=1)

    maximum = nondom_scores[I,:]

    '''
    Find intercepts of a hyper plane generated by 'maximum'
    points.
    '''
    points = maximum - ideal_point
    b = np.ones(points.shape[1])
    plane = np.linalg.solve(points, b)
    intercepts = 1/plane

    return (candidate_scores - ideal_point)/intercepts, ideal_point, intercepts

def associate(reference_points, normalized_candidate_scores, passing_number):
    '''
    Associates each candidate with a closest line generated
    by a reference point.

    Outputs two arrays:
    'assoc_table' has the same number of rows as normalized_candidate_scores,
        its first column contains reference point index and second - 
        distance to the line generated by it.
    'ref_count' is a 1D array of same length as reference_points.
        For each ref point it contains the number of associated
        solutions from candidates EXCLUDING last front.
    '''

    dist_matrix = np.zeros((normalized_candidate_scores.shape[0], reference_points.shape[0]))
    ref_count = np.zeros(reference_points.shape[0])

    '''
    Calculate distance from each solution to each line.
    TODO: Reimplement in C or Go
    '''
    for i, c in enumerate(normalized_candidate_scores):
        for j, p in enumerate(reference_points):
            diff_vector = c - p.dot(c) * p/np.sum(p**2)
            dist_matrix[i,j] = np.sqrt(np.sum(diff_vector**2))

    assoc_table = np.zeros((normalized_candidate_scores.shape[0], 2))
    assoc_table[:,0] = np.argmin(dist_matrix, axis=1)
    assoc_table[:,1] = np.min(dist_matrix, axis=1)

    for i in range(passing_number):
        ref_count[np.int(assoc_table[i,0])] += 1

    return assoc_table, ref_count

def niche(ref_count,
          assoc_table,
          points_to_choose_number,
          candidates,
          passing_number):
    '''
    From the last front choose points which will be added
    to the next generation.
    TODO: clean up the code and fix bug with duplicates
    TODO: fix argwhere bug
    '''

    '''
    Inputs:

    ref_count - array of references to refpoints
        index - ref point index
        value - number of references to this ref point
    assoc_table - array of associations between refpoints and solutions
        index - index of a candidate
        first column - index of associated refpoint
        second colum - sitance to closest refpoint
    points_to_choose_number - number of points we have to choose
    candidates - indices of candidates
    passing_number - number of candidates that already pass
    '''
    last_front_assoc_table = assoc_table[passing_number:,:]
    new_population = candidates[:passing_number]
    enum_assoc_table = np.zeros((len(assoc_table), 3))
    enum_assoc_table[:,1:] = assoc_table
    enum_assoc_table[:,0] = np.arange(0,len(assoc_table))

    k = 1
    while k <= points_to_choose_number:
        best_ref_points = np.argwhere(ref_count==np.min(ref_count)).T[0]

        best_ref_point = np.random.choice(best_ref_points)
        last_front_best = np.argwhere(last_front_assoc_table[:,0]==best_ref_point).T[0] + passing_number
        if last_front_best.shape[0] != 0:
            if ref_count[best_ref_point] == 0:
                last_front_bestest_index = np.argmin(enum_assoc_table[last_front_best,2])
                last_front_bestest = enum_assoc_table[last_front_best,:][last_front_bestest_index,0]
                new_population += [candidates[int(last_front_bestest)]]
            else:
                new_population += [candidates[np.random.choice(last_front_best)]]
            ref_count[best_ref_point] += 1
            last_front_assoc_table[last_front_best-passing_number, 0] = -1
            k+=1
        else:
            ref_count[best_ref_point] = 1e9

    return new_population


def visualize_ranks(population, figname, ranks=None):
    for i, s in enumerate(population):
        color = 'm'
        if type(ranks) is np.ndarray:
            if ranks[i] % 3 == 1:
                color = 'r'
            elif ranks[i] % 3 == 2:
                color = 'g'
            else:
                color = 'b'
        plt.scatter(*s, c=color)
    plt.savefig(figname)

def nsga3(initial_coords, div):

    popsize = initial_coords.shape[0]
    dim = initial_coords.shape[1]
    #visualize_ranks(initial_coords, '1_initial.png')

    '''
    Perform nondominated sort
    '''
    fronts, ranks = fast_non_dominated_sort(initial_coords)
    #visualize_ranks(initial_coords, '2_ranked.png', ranks)

    '''
    Make a set of candidates that will compete for the
    next generation
    '''
    candidates = []
    cutoff_number = popsize // 2
    candidates_number = 0

    for f in fronts:
        if candidates_number + len(f) < cutoff_number:
            candidates = candidates + f
            candidates_number += len(f)
        elif candidates_number + len(f) == cutoff_number:
            return candidates + f
        else:
            passing_number = len(candidates)
            points_to_choose_number = cutoff_number - passing_number
            candidates = candidates + f
            candidates_number += len(f)
            last_front = f
            break
    '''
    'candidates_number' - the amount of solutions that compete for
    next generation
    'candidates' - these solutions len(candidates) = candidates_number
    '''


    '''
    Generate reference points
    '''
    reference_points = get_reference_coords(div, dim)

    '''
    Visualize the reference points
    '''
    if dim== 2:
        fig = plt.figure()
        plt.scatter(reference_points[:,0], reference_points[:,1])
        plt.savefig('3_references.png')
    elif dim== 3:
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        ax.view_init(elev=10., azim=30)
        ax.scatter(reference_points[:,0], reference_points[:,1], reference_points[:,2])
        plt.savefig('3_references.png')

    '''
    Normalize candidate scores
    '''
    candidate_scores = initial_coords[candidates]
    nondom_scores = initial_coords[fronts[0]]

    normalized_candidate_scores,ideal_point,intercepts = normalize(candidate_scores, nondom_scores)

    '''
    Visualize normalized candidate scores with reference points
    '''
    if dim== 2:
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.set_xlim(-0.1,1.1)
        ax.set_ylim(-0.1,1.1)
        ax.scatter(normalized_candidate_scores[:,0],normalized_candidate_scores[:,1])

        for r in reference_points:
            x, y = r
            if x > y:
                ax.plot((0,1), (0,y/x), 'r-')
            elif y > x:
                ax.plot((0,x/y), (0,1), 'r-')
            else:
                ax.plot((0,1), (0,1), 'r-')

        plt.savefig('4_normalized.png')

    '''
    For each candidate point find out its nearest reference line and
    distance to it
    '''
    assoc_table, ref_count = associate(reference_points,
                                       normalized_candidate_scores,
                                       passing_number)

    '''
    Visualize the result
    '''
    if dim== 2:
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.set_xlim(-0.1,1.1)
        ax.set_ylim(-0.1,1.1)
        for i, s in enumerate(normalized_candidate_scores):
            ref_point = int(assoc_table[i,0])
            if ref_point%3 == 0:
                c = 'r'
            elif ref_point%3 == 1:
                c = 'g'
            else:
                c = 'b'
            ax.scatter(s[0], s[1], c=c)
        for i, r in enumerate(reference_points):
            if i%3 == 0:
                c = 'r--'
            elif i%3 == 1:
                c = 'g--'
            else:
                c = 'b--'
            x, y = r
            if x > y:
                ax.plot((0,1), (0,y/x), c)
            elif y > x:
                ax.plot((0,x/y), (0,1), c)
            else:
                ax.plot((0,1), (0,1), c)
        plt.savefig('5_associated.png')

    '''
    Niching: delete extra points
    '''
    new_population = niche(ref_count,
                           assoc_table,
                           points_to_choose_number,
                           candidates,
                           passing_number)

    '''
    Visualize the result
    '''

    new_pop_a = np.array(new_population)
    candidates_a = np.array(candidates)
    last_front_a = np.array(last_front)

    passed_last_front_a = new_pop_a[passing_number:]
    rejected_last_front_a = np.copy(last_front_a)
    default_pass_a = new_pop_a[:passing_number]

    normalized_initial_coords = (initial_coords - ideal_point) / intercepts

    for l in passed_last_front_a:
        rejected_last_front_a = rejected_last_front_a[rejected_last_front_a!=l]

    if dim== 2:
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.set_xlim(-0.1,1.1)
        ax.set_ylim(-0.1,1.1)
        for i, s in enumerate(normalized_initial_coords[passed_last_front_a]):
            ax.scatter(s[0], s[1], c='r', marker='*')
        for i, s in enumerate(normalized_initial_coords[rejected_last_front_a]):
            ax.scatter(s[0], s[1], c='r', marker='x')
        for i, s in enumerate(normalized_initial_coords[default_pass_a]):
            ax.scatter(s[0], s[1], c='b', marker='.')
        for i, r in enumerate(reference_points):
            if i%3 == 0:
                c = 'r--'
            elif i%3 == 1:
                c = 'g--'
            else:
                c = 'b--'
            x, y = r
            if x > y:
                ax.plot((0,1), (0,y/x), c)
            elif y > x:
                ax.plot((0,x/y), (0,1), c)
            else:
                ax.plot((0,1), (0,1), c)
        plt.savefig('6_niched.png')

    return new_population

if __name__ == '__main__':
    ''' Test case 1 '''
    np.random.seed(69)
    init = np.random.random_sample((100, 2))
    solution = nsga3(init, 5)
    true_solution = [15, 26, 59, 81, 83, 32, 5, 75, 55, 88, 91, 28, 64, 31, 34, 46, 84, 25, 20, 73, 96, 52, 72, 87, 4, 50, 57, 78, 1, 45, 65, 0, 53, 56, 49, 68, 61, 35, 90, 38, 48, 76, 51, 58, 7, 16, 33, 94, 17, 67]
    if solution != true_solution:
        print('TEST 1 FAILED')
    else:
        print('PASS')

    ''' Test case 2 '''
    np.random.seed(1337)
    init = np.random.random_sample((100, 2))
    solution = nsga3(init, 5)
    true_solution = [18, 26, 29, 44, 46, 52, 54, 91, 94, 33, 40, 42, 59, 86, 3, 6, 24, 99, 80, 25, 68, 74, 79, 15, 63, 8, 39, 78, 14, 28, 76, 34, 41, 53, 10, 47, 81, 89, 7, 90, 58, 72, 4, 32, 97, 50, 22, 30, 16, 88]
    if solution != true_solution:
        print('TEST 2 FAILED')
    else:
        print('PASS')

    ''' Test case 3 '''
    np.random.seed(42)
    init = np.random.random_sample((200, 2))
    solution = nsga3(init, 5)
    true_solution = [17, 25, 120, 124, 130, 152, 183, 195, 136, 34, 27, 69, 123, 26, 162, 77, 113, 60, 98, 5, 0, 156, 56, 91, 128, 179,
67, 70, 182, 191, 16, 197, 57, 63, 99, 96, 89, 121, 21, 101, 122, 109, 135, 175, 132, 59, 114, 52, 75, 95, 194, 199, 168, 40, 44, 140, 3, 82, 192, 157, 198, 36, 33, 37, 139, 93, 138, 31, 126, 146, 12, 78, 133, 1, 43, 46, 115, 6, 188, 189, 196, 4, 53, 160, 110, 47, 58, 154, 165, 163, 68, 105, 81, 19, 88, 35, 107, 148, 38, 108]
    if solution != true_solution:
        print('TEST 3 FAILED')
    else:
        print('PASS')


